/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedManagerBillsRouteImport } from './routes/_authenticated/manager/bills'
import { Route as AuthenticatedManagerDashboardRouteImport } from './routes/_authenticated/manager/dashboard'
import { Route as AuthenticatedManagerExpensesRouteImport } from './routes/_authenticated/manager/expenses'
import { Route as AuthenticatedManagerPaymentsRouteImport } from './routes/_authenticated/manager/payments'
import { Route as AuthenticatedManagerReportsRouteImport } from './routes/_authenticated/manager/reports'
import { Route as AuthenticatedOwnerBillsRouteImport } from './routes/_authenticated/owner/bills'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated/owner/dashboard'
import { Route as AuthenticatedOwnerExpensesRouteImport } from './routes/_authenticated/owner/expenses'
import { Route as AuthenticatedOwnerPaymentsRouteImport } from './routes/_authenticated/owner/payments'
import { Route as AuthenticatedOwnerRentRouteImport } from './routes/_authenticated/owner/rent'
import { Route as AuthenticatedOwnerReportsRouteImport } from './routes/_authenticated/owner/reports'
import { Route as AuthenticatedTenantDashboardRouteImport } from './routes/_authenticated/tenant/dashboard'
import { Route as AuthenticatedOwnerBuildingsIndexRouteImport } from './routes/_authenticated/owner/buildings/index'
import { Route as AuthenticatedOwnerBuildingsBuildingIdRouteImport } from './routes/_authenticated/owner/buildings/$buildingId'
import { Route as AuthenticatedOwnerFlatsBuildingIdRouteImport } from './routes/_authenticated/owner/flats/$buildingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerBillsRoute =
  AuthenticatedManagerBillsRouteImport.update({
    id: '/manager/bills',
    path: '/manager/bills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDashboardRoute =
  AuthenticatedManagerDashboardRouteImport.update({
    id: '/manager/dashboard',
    path: '/manager/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerExpensesRoute =
  AuthenticatedManagerExpensesRouteImport.update({
    id: '/manager/expenses',
    path: '/manager/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPaymentsRoute =
  AuthenticatedManagerPaymentsRouteImport.update({
    id: '/manager/payments',
    path: '/manager/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerReportsRoute =
  AuthenticatedManagerReportsRouteImport.update({
    id: '/manager/reports',
    path: '/manager/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerBillsRoute = AuthenticatedOwnerBillsRouteImport.update({
  id: '/owner/bills',
  path: '/owner/bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/owner/dashboard',
    path: '/owner/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerExpensesRoute =
  AuthenticatedOwnerExpensesRouteImport.update({
    id: '/owner/expenses',
    path: '/owner/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerPaymentsRoute =
  AuthenticatedOwnerPaymentsRouteImport.update({
    id: '/owner/payments',
    path: '/owner/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerRentRoute = AuthenticatedOwnerRentRouteImport.update({
  id: '/owner/rent',
  path: '/owner/rent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerReportsRoute =
  AuthenticatedOwnerReportsRouteImport.update({
    id: '/owner/reports',
    path: '/owner/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantDashboardRoute =
  AuthenticatedTenantDashboardRouteImport.update({
    id: '/tenant/dashboard',
    path: '/tenant/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerBuildingsIndexRoute =
  AuthenticatedOwnerBuildingsIndexRouteImport.update({
    id: '/owner/buildings/',
    path: '/owner/buildings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerBuildingsBuildingIdRoute =
  AuthenticatedOwnerBuildingsBuildingIdRouteImport.update({
    id: '/owner/buildings/$buildingId',
    path: '/owner/buildings/$buildingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerFlatsBuildingIdRoute =
  AuthenticatedOwnerFlatsBuildingIdRouteImport.update({
    id: '/owner/flats/$buildingId',
    path: '/owner/flats/$buildingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/manager/bills': typeof AuthenticatedManagerBillsRoute
  '/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/manager/expenses': typeof AuthenticatedManagerExpensesRoute
  '/manager/payments': typeof AuthenticatedManagerPaymentsRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/owner/bills': typeof AuthenticatedOwnerBillsRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/expenses': typeof AuthenticatedOwnerExpensesRoute
  '/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/owner/rent': typeof AuthenticatedOwnerRentRoute
  '/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/owner/buildings/$buildingId': typeof AuthenticatedOwnerBuildingsBuildingIdRoute
  '/owner/flats/$buildingId': typeof AuthenticatedOwnerFlatsBuildingIdRoute
  '/owner/buildings/': typeof AuthenticatedOwnerBuildingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/manager/bills': typeof AuthenticatedManagerBillsRoute
  '/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/manager/expenses': typeof AuthenticatedManagerExpensesRoute
  '/manager/payments': typeof AuthenticatedManagerPaymentsRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/owner/bills': typeof AuthenticatedOwnerBillsRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/expenses': typeof AuthenticatedOwnerExpensesRoute
  '/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/owner/rent': typeof AuthenticatedOwnerRentRoute
  '/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/owner/buildings/$buildingId': typeof AuthenticatedOwnerBuildingsBuildingIdRoute
  '/owner/flats/$buildingId': typeof AuthenticatedOwnerFlatsBuildingIdRoute
  '/owner/buildings': typeof AuthenticatedOwnerBuildingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/manager/bills': typeof AuthenticatedManagerBillsRoute
  '/_authenticated/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/_authenticated/manager/expenses': typeof AuthenticatedManagerExpensesRoute
  '/_authenticated/manager/payments': typeof AuthenticatedManagerPaymentsRoute
  '/_authenticated/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/_authenticated/owner/bills': typeof AuthenticatedOwnerBillsRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/_authenticated/owner/expenses': typeof AuthenticatedOwnerExpensesRoute
  '/_authenticated/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/_authenticated/owner/rent': typeof AuthenticatedOwnerRentRoute
  '/_authenticated/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/_authenticated/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/_authenticated/owner/buildings/$buildingId': typeof AuthenticatedOwnerBuildingsBuildingIdRoute
  '/_authenticated/owner/flats/$buildingId': typeof AuthenticatedOwnerFlatsBuildingIdRoute
  '/_authenticated/owner/buildings/': typeof AuthenticatedOwnerBuildingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/manager/bills'
    | '/manager/dashboard'
    | '/manager/expenses'
    | '/manager/payments'
    | '/manager/reports'
    | '/owner/bills'
    | '/owner/dashboard'
    | '/owner/expenses'
    | '/owner/payments'
    | '/owner/rent'
    | '/owner/reports'
    | '/tenant/dashboard'
    | '/owner/buildings/$buildingId'
    | '/owner/flats/$buildingId'
    | '/owner/buildings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/manager/bills'
    | '/manager/dashboard'
    | '/manager/expenses'
    | '/manager/payments'
    | '/manager/reports'
    | '/owner/bills'
    | '/owner/dashboard'
    | '/owner/expenses'
    | '/owner/payments'
    | '/owner/rent'
    | '/owner/reports'
    | '/tenant/dashboard'
    | '/owner/buildings/$buildingId'
    | '/owner/flats/$buildingId'
    | '/owner/buildings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/manager/bills'
    | '/_authenticated/manager/dashboard'
    | '/_authenticated/manager/expenses'
    | '/_authenticated/manager/payments'
    | '/_authenticated/manager/reports'
    | '/_authenticated/owner/bills'
    | '/_authenticated/owner/dashboard'
    | '/_authenticated/owner/expenses'
    | '/_authenticated/owner/payments'
    | '/_authenticated/owner/rent'
    | '/_authenticated/owner/reports'
    | '/_authenticated/tenant/dashboard'
    | '/_authenticated/owner/buildings/$buildingId'
    | '/_authenticated/owner/flats/$buildingId'
    | '/_authenticated/owner/buildings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager/bills': {
      id: '/_authenticated/manager/bills'
      path: '/manager/bills'
      fullPath: '/manager/bills'
      preLoaderRoute: typeof AuthenticatedManagerBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/dashboard': {
      id: '/_authenticated/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AuthenticatedManagerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/expenses': {
      id: '/_authenticated/manager/expenses'
      path: '/manager/expenses'
      fullPath: '/manager/expenses'
      preLoaderRoute: typeof AuthenticatedManagerExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/payments': {
      id: '/_authenticated/manager/payments'
      path: '/manager/payments'
      fullPath: '/manager/payments'
      preLoaderRoute: typeof AuthenticatedManagerPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/reports': {
      id: '/_authenticated/manager/reports'
      path: '/manager/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof AuthenticatedManagerReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/bills': {
      id: '/_authenticated/owner/bills'
      path: '/owner/bills'
      fullPath: '/owner/bills'
      preLoaderRoute: typeof AuthenticatedOwnerBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/expenses': {
      id: '/_authenticated/owner/expenses'
      path: '/owner/expenses'
      fullPath: '/owner/expenses'
      preLoaderRoute: typeof AuthenticatedOwnerExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/payments': {
      id: '/_authenticated/owner/payments'
      path: '/owner/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof AuthenticatedOwnerPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/rent': {
      id: '/_authenticated/owner/rent'
      path: '/owner/rent'
      fullPath: '/owner/rent'
      preLoaderRoute: typeof AuthenticatedOwnerRentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/reports': {
      id: '/_authenticated/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof AuthenticatedOwnerReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant/dashboard': {
      id: '/_authenticated/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof AuthenticatedTenantDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/buildings/': {
      id: '/_authenticated/owner/buildings/'
      path: '/owner/buildings'
      fullPath: '/owner/buildings/'
      preLoaderRoute: typeof AuthenticatedOwnerBuildingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/buildings/$buildingId': {
      id: '/_authenticated/owner/buildings/$buildingId'
      path: '/owner/buildings/$buildingId'
      fullPath: '/owner/buildings/$buildingId'
      preLoaderRoute: typeof AuthenticatedOwnerBuildingsBuildingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/flats/$buildingId': {
      id: '/_authenticated/owner/flats/$buildingId'
      path: '/owner/flats/$buildingId'
      fullPath: '/owner/flats/$buildingId'
      preLoaderRoute: typeof AuthenticatedOwnerFlatsBuildingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedManagerBillsRoute: typeof AuthenticatedManagerBillsRoute
  AuthenticatedManagerDashboardRoute: typeof AuthenticatedManagerDashboardRoute
  AuthenticatedManagerExpensesRoute: typeof AuthenticatedManagerExpensesRoute
  AuthenticatedManagerPaymentsRoute: typeof AuthenticatedManagerPaymentsRoute
  AuthenticatedManagerReportsRoute: typeof AuthenticatedManagerReportsRoute
  AuthenticatedOwnerBillsRoute: typeof AuthenticatedOwnerBillsRoute
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
  AuthenticatedOwnerExpensesRoute: typeof AuthenticatedOwnerExpensesRoute
  AuthenticatedOwnerPaymentsRoute: typeof AuthenticatedOwnerPaymentsRoute
  AuthenticatedOwnerRentRoute: typeof AuthenticatedOwnerRentRoute
  AuthenticatedOwnerReportsRoute: typeof AuthenticatedOwnerReportsRoute
  AuthenticatedTenantDashboardRoute: typeof AuthenticatedTenantDashboardRoute
  AuthenticatedOwnerBuildingsBuildingIdRoute: typeof AuthenticatedOwnerBuildingsBuildingIdRoute
  AuthenticatedOwnerFlatsBuildingIdRoute: typeof AuthenticatedOwnerFlatsBuildingIdRoute
  AuthenticatedOwnerBuildingsIndexRoute: typeof AuthenticatedOwnerBuildingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedManagerBillsRoute: AuthenticatedManagerBillsRoute,
  AuthenticatedManagerDashboardRoute: AuthenticatedManagerDashboardRoute,
  AuthenticatedManagerExpensesRoute: AuthenticatedManagerExpensesRoute,
  AuthenticatedManagerPaymentsRoute: AuthenticatedManagerPaymentsRoute,
  AuthenticatedManagerReportsRoute: AuthenticatedManagerReportsRoute,
  AuthenticatedOwnerBillsRoute: AuthenticatedOwnerBillsRoute,
  AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
  AuthenticatedOwnerExpensesRoute: AuthenticatedOwnerExpensesRoute,
  AuthenticatedOwnerPaymentsRoute: AuthenticatedOwnerPaymentsRoute,
  AuthenticatedOwnerRentRoute: AuthenticatedOwnerRentRoute,
  AuthenticatedOwnerReportsRoute: AuthenticatedOwnerReportsRoute,
  AuthenticatedTenantDashboardRoute: AuthenticatedTenantDashboardRoute,
  AuthenticatedOwnerBuildingsBuildingIdRoute:
    AuthenticatedOwnerBuildingsBuildingIdRoute,
  AuthenticatedOwnerFlatsBuildingIdRoute:
    AuthenticatedOwnerFlatsBuildingIdRoute,
  AuthenticatedOwnerBuildingsIndexRoute: AuthenticatedOwnerBuildingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
