/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedManagerDashboardRouteImport } from './routes/_authenticated/manager/dashboard'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated/owner/dashboard'
import { Route as AuthenticatedTenantDashboardRouteImport } from './routes/_authenticated/tenant/dashboard'
import { Route as AuthenticatedOwnerBuildingsIndexRouteImport } from './routes/_authenticated/owner/buildings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerDashboardRoute =
  AuthenticatedManagerDashboardRouteImport.update({
    id: '/manager/dashboard',
    path: '/manager/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/owner/dashboard',
    path: '/owner/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantDashboardRoute =
  AuthenticatedTenantDashboardRouteImport.update({
    id: '/tenant/dashboard',
    path: '/tenant/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerBuildingsIndexRoute =
  AuthenticatedOwnerBuildingsIndexRouteImport.update({
    id: '/owner/buildings/',
    path: '/owner/buildings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/owner/buildings/': typeof AuthenticatedOwnerBuildingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/owner/buildings': typeof AuthenticatedOwnerBuildingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/manager/dashboard': typeof AuthenticatedManagerDashboardRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/_authenticated/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/_authenticated/owner/buildings/': typeof AuthenticatedOwnerBuildingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/manager/dashboard'
    | '/owner/dashboard'
    | '/tenant/dashboard'
    | '/owner/buildings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/manager/dashboard'
    | '/owner/dashboard'
    | '/tenant/dashboard'
    | '/owner/buildings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/manager/dashboard'
    | '/_authenticated/owner/dashboard'
    | '/_authenticated/tenant/dashboard'
    | '/_authenticated/owner/buildings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager/dashboard': {
      id: '/_authenticated/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AuthenticatedManagerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant/dashboard': {
      id: '/_authenticated/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof AuthenticatedTenantDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/buildings/': {
      id: '/_authenticated/owner/buildings/'
      path: '/owner/buildings'
      fullPath: '/owner/buildings/'
      preLoaderRoute: typeof AuthenticatedOwnerBuildingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedManagerDashboardRoute: typeof AuthenticatedManagerDashboardRoute
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
  AuthenticatedTenantDashboardRoute: typeof AuthenticatedTenantDashboardRoute
  AuthenticatedOwnerBuildingsIndexRoute: typeof AuthenticatedOwnerBuildingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedManagerDashboardRoute: AuthenticatedManagerDashboardRoute,
  AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
  AuthenticatedTenantDashboardRoute: AuthenticatedTenantDashboardRoute,
  AuthenticatedOwnerBuildingsIndexRoute: AuthenticatedOwnerBuildingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
